"""A* path planning for navigation questions and top-down path rendering.

For each object-finding question (generated by :mod:`internscenes.questions`)
this module:

1. Builds a 2D occupancy grid from ``scene.json`` (room polygon + object
   footprints buffered by the Go2 radius).
2. Runs A* from the Go2 start pose to a collision-free goal near the target
   object.
3. Converts the continuous path into a discrete action sequence using the
   user's action vocabulary:

   - ``turn_left`` / ``turn_right`` (15°)
   - ``turn_left_big`` / ``turn_right_big`` (90°)
   - ``move_forward`` / ``move_backward`` (0.25 m per step)
4. Renders a top-down image in the same style as ``topdown.png`` but with
   start / goal markers and the planned path overlaid.
5. Writes per-question JSON files containing the trajectory, actions, and
   path coordinates.

Public entry point: :func:`plan_for_scene`.
"""
from __future__ import annotations

import argparse
import heapq
import json
import logging
import math
import os
from pathlib import Path
from typing import Any

import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Polygon, FancyArrowPatch
from matplotlib.transforms import Affine2D

logger = logging.getLogger(__name__)

# Action vocabulary constants (must match the user's specification).
TURN_LEFT = "turn_left"
TURN_RIGHT = "turn_right"
TURN_LEFT_BIG = "turn_left_big"
TURN_RIGHT_BIG = "turn_right_big"
MOVE_FORWARD = "move_forward"
MOVE_BACKWARD = "move_backward"

STEP_M = 0.25          # standard move distance
SMALL_TURN = math.radians(15.0)
BIG_TURN = math.radians(90.0)
GO2_R = 0.20           # Go2 footprint radius (circle)
GRID_RES = 0.05        # occupancy grid resolution in metres


def _normalize_angle(a: float) -> float:
    """Return angle in (-pi, pi]."""
    while a <= -math.pi:
        a += 2 * math.pi
    while a > math.pi:
        a -= 2 * math.pi
    return a


def _footprint_rect(b: list | dict) -> tuple[float, float, float, float, float]:
    """Return (cx, cy, w, h, yaw) for the XY footprint of a 3D bbox."""
    if isinstance(b, dict):
        b = [b.get("cx", 0), b.get("cy", 0), b.get("cz", 0),
             b.get("dx", 0), b.get("dy", 0), b.get("dz", 0),
             b.get("rot_x", 0), b.get("rot_y", 0), b.get("rot_z", 0)]
    cx, cy, dx, dy = b[0], b[1], b[3], b[4]
    return cx, cy, dx, dy, b[8]


def _point_in_polygon(x: float, y: float, polygon: np.ndarray) -> bool:
    """Ray-casting point-in-polygon test."""
    n = len(polygon)
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = polygon[i]
        xj, yj = polygon[j]
        if ((yi > y) != (yj > y)) and (x < (xj - xi) * (y - yi) / ((yj - yi) or 1e-12) + xi):
            inside = not inside
        j = i
    return inside


class GridMap:
    """Light-weight 2D occupancy grid for A* with rectangle obstacle checks."""

    def __init__(self, bounds: dict, polygon: np.ndarray,
                 obstacles: list[list[tuple[float, float]]],
                 resolution: float = GRID_RES, robot_radius: float = GO2_R):
        self.res = resolution
        self.robot_radius = robot_radius
        self.min_x = bounds["min_x"] - 1.0
        self.min_y = bounds["min_y"] - 1.0
        self.max_x = bounds["max_x"] + 1.0
        self.max_y = bounds["max_y"] + 1.0
        self.polygon = polygon
        self.obstacles = obstacles

        self.nx = int((self.max_x - self.min_x) / self.res) + 1
        self.ny = int((self.max_y - self.min_y) / self.res) + 1
        logger.info("grid: %dx%d cells (%.3fm)", self.nx, self.ny, self.res)

        # Pre-compute the wall-buffered walkable polygon: shrink the room outline
        # by the robot radius so the robot centre stays clear of walls.
        try:
            from shapely.geometry import Polygon as SPoly, Point as SPoint  # type: ignore
            sp = SPoly(polygon)
            self._walkable = sp.buffer(-robot_radius)
            self._use_shapely = True
        except Exception:  # pragma: no cover - fallback if shapely missing
            self._walkable = None
            self._use_shapely = False

    def _world(self, ix: int, iy: int) -> tuple[float, float]:
        return self.min_x + ix * self.res, self.min_y + iy * self.res

    def _index(self, x: float, y: float) -> tuple[int, int]:
        ix = int(round((x - self.min_x) / self.res))
        iy = int(round((y - self.min_y) / self.res))
        return max(0, min(ix, self.nx - 1)), max(0, min(iy, self.ny - 1))

    def is_free(self, x: float, y: float) -> bool:
        """Check whether a world point is walkable (inside buffered polygon, clear of obstacles)."""
        if self._use_shapely:
            try:
                from shapely.geometry import Point as SPoint  # type: ignore
                if not self._walkable.contains(SPoint(x, y)):
                    return False
            except Exception:
                if not _point_in_polygon(x, y, self.polygon):
                    return False
        else:
            if not _point_in_polygon(x, y, self.polygon):
                return False

        r = self.robot_radius
        for rect in self.obstacles:
            if _circle_rect_intersect(x, y, r, rect):
                return False
        return True

    def is_free_index(self, ix: int, iy: int) -> bool:
        return self.is_free(*self._world(ix, iy))

    def neighbours(self, ix: int, iy: int) -> list[tuple[int, int, float]]:
        """8-neighbour expansion with Euclidean step cost."""
        out: list[tuple[int, int, float]] = []
        for dx, dy, cost in (
            (1, 0, 1.0), (-1, 0, 1.0), (0, 1, 1.0), (0, -1, 1.0),
            (1, 1, math.sqrt(2)), (1, -1, math.sqrt(2)),
            (-1, 1, math.sqrt(2)), (-1, -1, math.sqrt(2)),
        ):
            nx_, ny_ = ix + dx, iy + dy
            if 0 <= nx_ < self.nx and 0 <= ny_ < self.ny and self.is_free_index(nx_, ny_):
                out.append((nx_, ny_, cost * self.res))
        return out


def _rect_vertices(cx: float, cy: float, w: float, h: float, yaw: float
                   ) -> list[tuple[float, float]]:
    """Return the four corners of an oriented rectangle in world coordinates."""
    corners = [(-w / 2, -h / 2), (w / 2, -h / 2), (w / 2, h / 2), (-w / 2, h / 2)]
    cos_y, sin_y = math.cos(yaw), math.sin(yaw)
    out = []
    for lx, ly in corners:
        wx = cx + lx * cos_y - ly * sin_y
        wy = cy + lx * sin_y + ly * cos_y
        out.append((wx, wy))
    return out


def _circle_rect_intersect(px: float, py: float, r: float,
                           rect: list[tuple[float, float]]) -> bool:
    """Return True if the circle (px,py,r) intersects the convex quadrilateral ``rect``."""
    # 1) Circle centre inside rectangle -> intersect.
    # Use cross-product edge tests for the convex quad.
    inside = True
    n = len(rect)
    for i in range(n):
        x0, y0 = rect[i]
        x1, y1 = rect[(i + 1) % n]
        ex, ey = x1 - x0, y1 - y0
        # outward normal (for CCW rect)
        nx_, ny_ = ey, -ex
        if (px - x0) * nx_ + (py - y0) * ny_ > 0:
            inside = False
            break
    if inside:
        return True

    # 2) Distance from centre to any edge < r -> intersect.
    for i in range(n):
        x0, y0 = rect[i]
        x1, y1 = rect[(i + 1) % n]
        ex, ey = x1 - x0, y1 - y0
        len_e = math.hypot(ex, ey)
        if len_e == 0:
            continue
        # Project centre onto edge segment.
        t = max(0.0, min(1.0, ((px - x0) * ex + (py - y0) * ey) / (len_e * len_e)))
        closest_x = x0 + t * ex
        closest_y = y0 + t * ey
        if (px - closest_x) ** 2 + (py - closest_y) ** 2 <= r * r:
            return True

    # 3) Any corner inside circle -> intersect.
    for x, y in rect:
        if (px - x) ** 2 + (py - y) ** 2 <= r * r:
            return True
    return False


# Categories that are attached to walls and should not block the floor plan.
_NON_BLOCKING_CATEGORIES = {"picture", "window", "doorframe", "wrap"}


def _build_obstacles(objects: list[dict]) -> list[list[tuple[float, float]]]:
    """Convert object bboxes to oriented rectangles (lists of 4 corner tuples).

    Wall-mounted decorative objects (pictures, windows, doorframes, wraps) are
    excluded because they do not occupy walkable floor space.
    """
    obs: list[list[tuple[float, float]]] = []
    for o in objects:
        cat = o.get("category", "").lower()
        if cat in _NON_BLOCKING_CATEGORIES:
            continue
        b = o.get("bbox") or [
            o["position_m"]["x"], o["position_m"]["y"], o["position_m"]["z"],
            o["size_m"]["length"], o["size_m"]["width"], o["size_m"]["height"],
            o["rotation_rad"]["x"], o["rotation_rad"]["y"], o["rotation_rad"]["z"],
        ]
        cx, cy, w, h, yaw = _footprint_rect(b)
        if w <= 0 or h <= 0:
            continue
        obs.append(_rect_vertices(cx, cy, w, h, yaw))
    return obs


def _reachable_component(grid: GridMap, start_idx: tuple[int, int]) -> set[tuple[int, int]]:
    """BFS flood-fill of all free cells reachable from ``start_idx``."""
    visited: set[tuple[int, int]] = set([start_idx])
    queue = [start_idx]
    while queue:
        cx, cy = queue.pop(0)
        for nx_, ny_, _ in grid.neighbours(cx, cy):
            if (nx_, ny_) not in visited:
                visited.add((nx_, ny_))
                queue.append((nx_, ny_))
    return visited


def _nearest_in_component(grid: GridMap, component: set[tuple[int, int]],
                          goal: tuple[float, float]) -> tuple[int, int]:
    """Return the cell in ``component`` closest to ``goal``."""
    best = None
    best_d = float("inf")
    gx, gy = goal
    for ix, iy in component:
        wx, wy = grid._world(ix, iy)
        d = (wx - gx) ** 2 + (wy - gy) ** 2
        if d < best_d:
            best_d = d
            best = (ix, iy)
    assert best is not None
    return best


def astar(grid: GridMap, start: tuple[float, float], goal: tuple[float, float],
          component: set[tuple[int, int]] | None = None,
          max_iters: int = 500_000,
          goal_tolerance_m: float = 0.30) -> tuple[list[tuple[float, float]], float] | tuple[None, float]:
    """A* search on the grid; returns (path, distance_to_goal_m).

    The raw ``goal`` is usually inside the target object.  The planner first
    finds the closest reachable cell in the start's connected component and
    plans to that point.  This guarantees a path whenever the room itself is
    connected, while honestly reporting how close to the object centre the
    robot can physically get.

    ``component`` can be precomputed from ``_reachable_component`` so the BFS
    is not repeated across many questions in the same scene.
    """
    sx, sy = grid._index(*start)
    if not grid.is_free_index(sx, sy):
        logger.warning("start cell is not free: %s", start)
        return None, float("inf")

    if component is None or (sx, sy) not in component:
        component = _reachable_component(grid, (sx, sy))

    gx, gy = grid._index(*goal)

    # Case 1: the exact goal cell (or a cell within tolerance) is reachable.
    reachable_goal = None
    best_d = float("inf")
    for ix, iy in component:
        wx, wy = grid._world(ix, iy)
        d = math.hypot(wx - goal[0], wy - goal[1])
        if d <= goal_tolerance_m and d < best_d:
            best_d = d
            reachable_goal = (ix, iy)

    # Case 2: settle for the closest reachable cell to the object centre.
    if reachable_goal is None:
        reachable_goal = _nearest_in_component(grid, component, goal)
        gwx, gwy = grid._world(*reachable_goal)
        best_d = math.hypot(gwx - goal[0], gwy - goal[1])
        logger.info("goal is occupied; planning to closest reachable point "
                    "(%.2f, %.2f) at distance %.2fm", gwx, gwy, best_d)

    # Standard A* to the chosen reachable goal cell.
    gx, gy = reachable_goal
    open_set: list[tuple[float, int, int, int]] = []
    counter = 0
    g_score = {(sx, sy): 0.0}
    came_from: dict[tuple[int, int], tuple[int, int] | None] = {(sx, sy): None}
    heapq.heappush(open_set, (0.0, counter, sx, sy))

    while open_set:
        _, _, cx, cy = heapq.heappop(open_set)
        if (cx, cy) == (gx, gy):
            path_idx: list[tuple[int, int]] = []
            cur: tuple[int, int] | None = (cx, cy)
            while cur is not None:
                path_idx.append(cur)
                cur = came_from[cur]
            path_idx.reverse()
            return [grid._world(ix, iy) for ix, iy in path_idx], best_d

        if len(came_from) > max_iters:
            logger.warning("A* exceeded max iterations")
            return None, best_d

        for nx_, ny_, step_cost in grid.neighbours(cx, cy):
            tentative = g_score.get((cx, cy), float("inf")) + step_cost
            if tentative < g_score.get((nx_, ny_), float("inf")):
                came_from[(nx_, ny_)] = (cx, cy)
                g_score[(nx_, ny_)] = tentative
                counter += 1
                heapq.heappush(open_set, (tentative + 0.0, counter, nx_, ny_))

    logger.warning("A* could not find a path from %s to %s", start, goal)
    return None, best_d


def _resample_path(path: list[tuple[float, float]], step_m: float = STEP_M) -> list[tuple[float, float]]:
    """Resample a path so consecutive points are roughly ``step_m`` apart."""
    if not path:
        return path
    out = [path[0]]
    accumulated = 0.0
    for i in range(1, len(path)):
        x0, y0 = path[i - 1]
        x1, y1 = path[i]
        seg_len = math.hypot(x1 - x0, y1 - y0)
        if seg_len == 0:
            continue
        dx, dy = (x1 - x0) / seg_len, (y1 - y0) / seg_len
        while accumulated + seg_len >= step_m:
            need = step_m - accumulated
            last = out[-1]
            out.append((last[0] + dx * need, last[1] + dy * need))
            x0, y0 = out[-1]
            seg_len -= need
            accumulated = 0.0
        accumulated += seg_len
    if out[-1] != path[-1]:
        out.append(path[-1])
    return out


def _discrete_turn(delta: float) -> list[str]:
    """Decompose a heading change into 15°/90° turn actions."""
    actions: list[str] = []
    delta = _normalize_angle(delta)
    # Prefer big turns first to keep sequences short.
    while abs(delta) >= BIG_TURN - 1e-6:
        if delta > 0:
            actions.append(TURN_LEFT_BIG)
            delta -= BIG_TURN
        else:
            actions.append(TURN_RIGHT_BIG)
            delta += BIG_TURN
    while abs(delta) >= SMALL_TURN - 1e-6:
        if delta > 0:
            actions.append(TURN_LEFT)
            delta -= SMALL_TURN
        else:
            actions.append(TURN_RIGHT)
            delta += SMALL_TURN
    return actions


def path_to_actions(path: list[tuple[float, float]],
                    initial_yaw: float = -math.pi / 2,
                    step_m: float = STEP_M) -> dict[str, Any]:
    """Convert a continuous path into discrete turn / move actions.

    Returns a dict with ``actions``, ``trajectory`` (poses with x, y, yaw),
    and ``path_waypoints``.
    """
    if len(path) < 2:
        return {"actions": [], "trajectory": [], "path_waypoints": path}

    waypoints = _resample_path(path, step_m)
    trajectory: list[dict[str, Any]] = []
    actions: list[str] = []
    yaw = initial_yaw
    trajectory.append({"x": waypoints[0][0], "y": waypoints[0][1], "yaw_rad": yaw,
                       "action": None, "step": 0})

    for i in range(1, len(waypoints)):
        x0, y0 = waypoints[i - 1]
        x1, y1 = waypoints[i]
        dx, dy = x1 - x0, y1 - y0
        dist = math.hypot(dx, dy)
        target_yaw = math.atan2(dy, dx)

        delta = _normalize_angle(target_yaw - yaw)
        turns = _discrete_turn(delta)
        actions.extend(turns)
        yaw = target_yaw

        n_forward = int(round(dist / step_m))
        fx, fy = x0, y0
        for _ in range(n_forward):
            actions.append(MOVE_FORWARD)
            fx += step_m * math.cos(yaw)
            fy += step_m * math.sin(yaw)
            trajectory.append({"x": fx, "y": fy, "yaw_rad": yaw,
                               "action": MOVE_FORWARD, "step": len(actions)})

    # Add final pose.
    trajectory.append({"x": waypoints[-1][0], "y": waypoints[-1][1], "yaw_rad": yaw,
                       "action": None, "step": len(actions)})

    return {
        "actions": actions,
        "trajectory": trajectory,
        "path_waypoints": waypoints,
        "total_distance_m": sum(math.hypot(waypoints[i][0] - waypoints[i - 1][0],
                                           waypoints[i][1] - waypoints[i - 1][1])
                               for i in range(1, len(waypoints))),
        "num_steps": len(actions),
    }


def _draw_rotated_bbox(ax, b: list | dict, color: str = "#d94f4f") -> None:
    """Draw an object's XY footprint (same style as topdown.py)."""
    cx, cy, w, h, yaw = _footprint_rect(b)
    t = Affine2D().translate(cx, cy).rotate(yaw).translate(-cx, -cy)
    rect = Rectangle((cx - w / 2, cy - h / 2), w, h,
                     facecolor=color, edgecolor="#a03030", alpha=0.35, lw=0.6)
    rect.set_transform(t + ax.transData)
    ax.add_patch(rect)


def render_path_topdown(scene_json: dict, question: dict, path: list[tuple[float, float]],
                        actions: dict[str, Any], out_path: str | Path,
                        title_suffix: str | None = None) -> None:
    """Render a top-down image matching ``topdown.png`` style with start/goal/path."""
    polygon = np.array(scene_json.get("room_interior_polygon_xy_m", []), dtype=float)
    objects = scene_json.get("objects", [])

    dims = scene_json.get("room_dimensions_m", {})
    pad = 0.6
    bx0 = dims.get("min_x", polygon[:, 0].min()) - pad
    bx1 = dims.get("max_x", polygon[:, 0].max()) + pad
    by0 = dims.get("min_y", polygon[:, 1].min()) - pad
    by1 = dims.get("max_y", polygon[:, 1].max()) + pad

    fig, ax = plt.subplots(figsize=(7, 7))
    ax.set_xlim(bx0, bx1)
    ax.set_ylim(by0, by1)
    ax.set_aspect("equal")

    # Walkable interior polygon.
    if len(polygon) >= 3:
        ax.add_patch(Polygon(polygon, closed=True, facecolor="#7fbf7f",
                             edgecolor="#2a7f2a", alpha=0.18, lw=1.2,
                             label="walkable interior"))

    # Obstacle footprints.
    for o in objects:
        bbox = o.get("bbox")
        if bbox is None:
            # Reconstruct from position/size/rotation.
            pos = o.get("position_m", {})
            size = o.get("size_m", {})
            rot = o.get("rotation_rad", {})
            bbox = [pos.get("x", 0), pos.get("y", 0), pos.get("z", 0),
                    size.get("length", 0), size.get("width", 0), size.get("height", 0),
                    rot.get("x", 0), rot.get("y", 0), rot.get("z", 0)]
        _draw_rotated_bbox(ax, bbox)

    # Path line.
    if path:
        xs = [p[0] for p in path]
        ys = [p[1] for p in path]
        ax.plot(xs, ys, "-", color="#1f77b4", linewidth=2.5, alpha=0.85, zorder=4,
                label="planned path")

    # Start marker (green circle + arrow).
    start = question["go2_position_m"]
    sx, sy = start["x"], start["y"]
    ax.add_patch(plt.Circle((sx, sy), GO2_R, color="#2ca02c", alpha=0.9, zorder=6,
                            label="start"))
    ax.annotate("", xy=(sx + 0.35 * math.cos(-math.pi / 2), sy + 0.35 * math.sin(-math.pi / 2)),
                xytext=(sx, sy),
                arrowprops=dict(arrowstyle="->", color="#1a5c1a", lw=2.5), zorder=7)

    # Goal marker (red star).
    goal = question["target_position_m"]
    gx, gy = goal["x"], goal["y"]
    ax.plot(gx, gy, "*", color="#d62728", markersize=18, markeredgecolor="white",
            markeredgewidth=1.5, zorder=8, label="goal")

    title = f"{question.get('scene_id', '')}  —  {question.get('question', '')}"
    if title_suffix:
        title += f"\n{title_suffix}"
    title += f"\npath steps: {actions.get('num_steps', 0)}  distance: {actions.get('total_distance_m', 0):.2f}m"
    ax.set_title(title, fontsize=10)
    ax.grid(True, alpha=0.25)
    ax.set_xlabel("X (m)")
    ax.set_ylabel("Y (m)")
    ax.legend(loc="upper left", fontsize=8, framealpha=0.9)
    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=150)
    plt.close()


def plan_for_scene(scene_id: str, root: Path | None = None,
                   questions_n: int | None = None,
                   grid_res: float = GRID_RES) -> dict[str, Any]:
    """Plan A* paths for every question of a scene and render top-down images.

    Args:
        scene_id: e.g. ``scannet/scene0001_00``.
        root: project root (defaults to parent of the package).
        questions_n: optional limit on number of questions to process.
        grid_res: occupancy grid resolution.

    Returns:
        Summary dict with paths and per-question results.
    """
    if root is None:
        root = Path(__file__).resolve().parents[2]
    root = Path(root)

    norm_dir = root / "output" / "normalized" / scene_id.replace("/", "_")
    questions_file = norm_dir / "questions.jsonl"
    scene_file = norm_dir / "scene.json"
    out_dir = norm_dir / "questions"

    if not questions_file.exists():
        raise FileNotFoundError(f"questions file not found: {questions_file}")
    if not scene_file.exists():
        raise FileNotFoundError(f"scene file not found: {scene_file}")

    with open(scene_file, encoding="utf-8") as fh:
        scene_json = json.load(fh)

    questions: list[dict] = []
    with open(questions_file, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                questions.append(json.loads(line))
    if questions_n is not None:
        questions = questions[:questions_n]

    polygon = np.array(scene_json.get("room_interior_polygon_xy_m", []), dtype=float)
    if len(polygon) < 3:
        logger.warning("no room interior polygon; using bbox fallback")
        dims = scene_json.get("room_dimensions_m", {})
        polygon = np.array([
            [dims["min_x"], dims["min_y"]], [dims["max_x"], dims["min_y"]],
            [dims["max_x"], dims["max_y"]], [dims["min_x"], dims["max_y"]],
        ], dtype=float)

    bounds = scene_json.get("room_dimensions_m", {})
    obstacles = _build_obstacles(scene_json.get("objects", []))
    grid = GridMap(bounds, polygon, obstacles, resolution=grid_res)

    results: list[dict] = []
    out_dir.mkdir(parents=True, exist_ok=True)

    # Questions in a scene almost always share the same robot start pose, so
    # precompute the reachable component once and reuse it for speed.
    first_start = (questions[0]["go2_position_m"]["x"],
                   questions[0]["go2_position_m"]["y"])
    s0x, s0y = grid._index(*first_start)
    reach_component: set[tuple[int, int]] | None = None
    if grid.is_free_index(s0x, s0y):
        reach_component = _reachable_component(grid, (s0x, s0y))
        logger.info("precomputed reachable component: %d cells", len(reach_component))

    for idx, q in enumerate(questions, 1):
        start = (q["go2_position_m"]["x"], q["go2_position_m"]["y"])
        goal = (q["target_position_m"]["x"], q["target_position_m"]["y"])

        path, goal_reach_m = astar(grid, start, goal, component=reach_component)
        if path is None:
            logger.warning("[%d/%d] no path for: %s", idx, len(questions), q.get("question"))
            results.append({
                "question_index": idx,
                "question": q.get("question"),
                "success": False,
                "reason": "astar_failed",
            })
            continue

        actions = path_to_actions(path)
        q_out_dir = out_dir / f"q{idx:03d}"
        q_out_dir.mkdir(parents=True, exist_ok=True)

        img_path = q_out_dir / "topdown_path.png"
        render_path_topdown(
            scene_json, q, path, actions, img_path,
            title_suffix=f"A* path  |  {len(actions['actions'])} actions"
        )

        record = {
            "question_index": idx,
            "scene_id": q.get("scene_id"),
            "question": q.get("question"),
            "question_en": q.get("question_en"),
            "target_category": q.get("target_category"),
            "target_color": q.get("target_color"),
            "success": True,
            "start_m": {"x": start[0], "y": start[1]},
            "goal_m": {"x": goal[0], "y": goal[1]},
            "actual_goal_m": {"x": path[-1][0], "y": path[-1][1]},
            "goal_reach_distance_m": goal_reach_m,
            "actions": actions["actions"],
            "trajectory": actions["trajectory"],
            "path_waypoints": [{"x": x, "y": y} for x, y in actions["path_waypoints"]],
            "raw_path_waypoints": [{"x": x, "y": y} for x, y in path],
            "total_distance_m": actions["total_distance_m"],
            "num_steps": actions["num_steps"],
            "topdown_path_image": str(img_path.relative_to(root)),
        }
        with open(q_out_dir / "trajectory.json", "w", encoding="utf-8") as fh:
            json.dump(record, fh, ensure_ascii=False, indent=2)

        # Also write a compact actions-only file for easy reading.
        with open(q_out_dir / "actions.json", "w", encoding="utf-8") as fh:
            json.dump({
                "question": q.get("question"),
                "actions": actions["actions"],
                "num_actions": len(actions["actions"]),
            }, fh, ensure_ascii=False, indent=2)

        results.append(record)
        logger.info("[%d/%d] planned %d actions -> %s", idx, len(questions),
                    len(actions["actions"]), q_out_dir)

    summary = {
        "scene_id": scene_id,
        "num_questions": len(questions),
        "successful": sum(1 for r in results if r.get("success")),
        "output_dir": str(out_dir.relative_to(root)),
        "results": results,
    }
    with open(out_dir / "summary.json", "w", encoding="utf-8") as fh:
        json.dump(summary, fh, ensure_ascii=False, indent=2)
    logger.info("summary: %d/%d succeeded", summary["successful"], summary["num_questions"])
    return summary


def main() -> int:
    ap = argparse.ArgumentParser(description="Plan A* paths for navigation questions")
    ap.add_argument("scene", help="scene id, e.g. scannet/scene0001_00")
    ap.add_argument("--root", type=Path, default=None,
                    help="project root (default: auto-detect)")
    ap.add_argument("--n", type=int, dest="questions_n", default=None,
                    help="process only the first N questions")
    ap.add_argument("--grid-res", type=float, default=GRID_RES,
                    help=f"occupancy grid resolution in metres (default: {GRID_RES})")
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    plan_for_scene(args.scene, root=args.root, questions_n=args.questions_n,
                   grid_res=args.grid_res)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
